# Generated by Django 3.2.4 on 2021-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=50)),
                ('date_time', models.IntegerField()),
                ('image_name', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
