# Generated by Django 3.2.4 on 2021-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_event_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.CharField(default='win the price', max_length=50),
        ),
    ]
