# Generated by Django 3.2.4 on 2021-06-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_event_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
    ]
