# Generated by Django 3.2.4 on 2021-06-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='registration',
        ),
    ]
