# Generated by Django 3.2.4 on 2021-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_form_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.AddField(
            model_name='registration',
            name='player_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='player_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='player_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='player_4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=35),
        ),
    ]
