# Generated by Django 3.2.4 on 2021-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_winners_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_group',
            field=models.CharField(default='', max_length=200),
        ),
    ]
