# Generated by Django 3.2.4 on 2021-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_event_whatsapp_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('desc', models.CharField(default='', max_length=50)),
                ('image_name', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='static/')),
                ('members', models.CharField(default='', max_length=2)),
                ('whatsapp_group', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
