# Generated by Django 3.2.4 on 2021-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210722_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='whatsapp_group',
            new_name='descord',
        ),
    ]
